/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    BoxPlotChart: typeof import('./src/components/charts/BoxPlotChart.vue')['default']
    ChordDiagram: typeof import('./src/components/charts/ChordDiagram.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    GlobalMessage: typeof import('./src/components/common/GlobalMessage.vue')['default']
    HeatmapChart: typeof import('./src/components/charts/HeatmapChart.vue')['default']
    MapChart: typeof import('./src/components/charts/MapChart.vue')['default']
    NetworkChart: typeof import('./src/components/charts/NetworkChart.vue')['default']
    ParetoChart: typeof import('./src/components/charts/ParetoChart.vue')['default']
    RadarChart: typeof import('./src/components/charts/RadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SankeyChart: typeof import('./src/components/charts/SankeyChart.vue')['default']
    Scatter3DChart: typeof import('./src/components/charts/Scatter3DChart.vue')['default']
    SunburstChart: typeof import('./src/components/charts/SunburstChart.vue')['default']
    TimelineChart: typeof import('./src/components/charts/TimelineChart.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
